name: Go
on:
  pull_request:
    paths:
      - go/**
      - .github/workflows/go.yml
  push:
    branches:
      - master

permissions:
  contents: write
  deployments: write

concurrency:
  group: go-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          # ci is set to go1.19 to match developer setups
          go-version: 1.19.2
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.50.0
          working-directory: go

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.2
      - name: test
        working-directory: ./go
        run: make test

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.2
      - name: Run coverage
        working-directory: ./go
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: go/coverage.txt
          flags: go
          fail_ci_if_error: true

  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: Run benchmark
        working-directory: ./go
        run: make bench | tee output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark
          tool: 'go'
          output-file-path: ./go/output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '50%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@crodriguezvega'
